-- ============================================================
-- ShopSphere 360
-- Forecast Table (Predictive Analytics)
-- ============================================================

USE shopsphere360;

CREATE TABLE IF NOT EXISTS fact_forecast (
    ForecastKey BIGINT AUTO_INCREMENT PRIMARY KEY,
    ForecastType VARCHAR(50) NOT NULL,
    PeriodLabel DATE NOT NULL,
    ProductKey INT NULL,
    PredictedValue DECIMAL(18,2) NOT NULL,
    ConfidenceLower DECIMAL(18,2) NULL,
    ConfidenceUpper DECIMAL(18,2) NULL,
    ModelName VARCHAR(100) NOT NULL,
    GeneratedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_forecast_product
        FOREIGN KEY (ProductKey)
        REFERENCES dim_product(ProductKey),

    INDEX idx_forecast_type (ForecastType),
    INDEX idx_forecast_date (PeriodLabel),
    INDEX idx_forecast_type_date (ForecastType, PeriodLabel)
);

-- Sample seed data will be generated by python/forecast.py
-- INSERT statements are generated by the Python forecasting script